### ISSUE TITLE
Ignores previous elements if they have the same name.

### ISSUE THREAD

**Issue by gwilakers** [chilts/data2xml#15]
If you have, for example, xml that looks like:

&lt;AccountData&gt;
            &lt;Data&gt;
                &lt;Name&gt;Company&lt;/Name&gt;
                &lt;Value&gt;Company Name&lt;/Value&gt;
            &lt;/Data&gt;
            &lt;Data&gt;
                &lt;Name&gt;Language&lt;/Name&gt;
                &lt;Value&gt;ENGLISH&lt;/Value&gt;
            &lt;/Data&gt;
            &lt;Data&gt;
                &lt;Name&gt;Status&lt;/Name&gt;
                &lt;Value&gt;ACTIVE&lt;/Value&gt;
            &lt;/Data&gt;
&lt;/AccountData&gt;

This will only print out the last "&lt;Data&gt;", ignoring the previous two.

**Comment by gwilakers** [comment]
I ended up figuring this one out late Friday and forgot to post an

**Comment by gwilakers** [comment]
I ended up figuring this one out late Friday and forgot to post an answer and close. Here is what I ended up doing to get around elements with the same name:

```
'AccountData' : [
        {
          Data : {
            'Name' : 'Some name.',
            'Value' : 'Some value.'
          }
        },
        {
          Data : {
            'Name' : 'Some name.',
            'Value' : 'Some value.'
          },
        },
        {
          Data : {
            'Name' : 'Some name.',
            'Value' : 'Some value.'
          },
        }
      ]
```

Basically an array of objects, with the actual objects being inside of those. A little hacky I think, but this is the only way to get around how JSON views objects with the same name.

**Comment by chilts** [comment]
Yeah, I saw this over the weekend and figured it would be an array (and yes, the underlying problem is just how objects are). Thanks for raising ... and closing. :)
