### ISSUE TITLE
No support for self-closing elements?

### ISSUE THREAD

**Issue by Adelost** [chilts/data2xml#19]
I need to create a self-closing tag similar to this:

    <Node name= "foo" />'

Is it supported or can it be added in the near future? 

I can only get the following:

    <Node name="foo"></Node>

Using this object:

    Foo: { _attr: { name: "foo" } }

If you are thinking of adding it, it could perhaps be automatic if no children other than `_attr` is specified. If there is someone who do not want a self-closing tag they can always set `_value` to an empty string.

**Comment by chilts** [comment]
Try setting the config option `null` to `empty`. Then you can do this:

```
Foo: {
  _attr : { name: 'foo' },
  _value : null
}
```

This should print out `<Foo name="foo" />`.

Let me know how it goes! :)

**Comment by chilts** [comment]
Sorry, set it to `closed` not `empty`. Empty will give you what you have above, closed should give you your desired behaviour.

Perhaps this could be made nicer if `_value` is not provided but that should help you for now.

**Comment by Adelost** [comment]
Works great, thanks!
