### ISSUE TITLE
CDATA closing disappear 

### ISSUE THREAD

**Issue by tbouchnafa** [chilts/data2xml#20]
Hi, All, 

i am using `data2xml` and got an error converting `json`  to `xml`
Here is an example code snippet where this occur: 

```javascript
var options = {attrProp: '@', valProp: '#', cdataProp: '%', xmlDecl: false};
var data2xml = require('data2xml');
var js2xml = data2xml(options);

var obj = {
    property: [
        {"@": {name: "title"}, "%": "Test"},
        {"@": {name: "description"}, "%": "TestDocument"}
    ]
};

var text = 'some thing here <widget>' + js2xml('document', obj) + '</widget> and some text here too';
console.log('\ntext before: \n' + text);

var xml = js2xml("text", {"%": text});
console.log('\nxml before: \n' + xml);
```

the problem occurs when converting the text on the line: 
```javascript
var xml = js2xml("text", {"%": text});
```
I get this `string`: 
```xml 
<text><![CDATA[some thing here <widget><document><property name="title"><![CDATA[Test</property><property name="description"><![CDATA[TestDocument]]></property></document></widget> and some text here too]]></text>
```

You can see that the CDATA closing disappear for the `property` with the name `title` :
```xml
<property name="title"><![CDATA[Test</property>
```

Can you please confirm & fix this ? 
Regards

**Comment by chilts** [comment]
Hiya,

Thanks for raising this. I see what you're doing. You're making the XML and then reinserting it as a CDATA section in the 2nd one.

According to the first two answers here - http://stackoverflow.com/questions/223652/is-there-a-way-to-escape-a-cdata-end-token-in-xml - putting a CDATA inside another can't be done, so I figure this will be the best way to escape it. You're right, it does disappear and that's the way I originally did it - though it's obviously wrong! :)

Anyway, am going to change this line:

```
         }else if(data[opts.cdataProp]){
-            element += '<![CDATA['+data[opts.cdataProp].replace(']]>','')+']]>';
+            element += '<![CDATA['+data[opts.cdataProp].replace(']]>',']]]]><![CDATA[>')+']]>';
         }
```

Hopefully that should do it. :) I'll ping back here once I've made the changes and re-released.

**Comment by chilts** [comment]
Released as v1.2.3. Cheers for raising this issue @tbouchnafa.

**Comment by tbouchnafa** [comment]
Thanks a lot @chilts for the fix, it works like rinking water :+1: :100:

**Comment by tbouchnafa** [comment]
Sorry to reopen this: 
I still get an error, CDATA was escaped correctly by the second element but not by the first 

```javascript
var options = {attrProp: '@', valProp: '#', cdataProp: '%', xmlDecl: false};
var data2xml = require('data2xml');
var js2xml = data2xml(options);

var obj = {
    property: [
        {"@": {name: "title"}, "%": "Download"},
        {"@": {name: "description"}, "%": "Download"}
    ]
};

var text = 'some thing here ' + js2xml('document', obj) + ' and some text here too';

console.log('\ntext before: \n' + text);

var xml = js2xml("text", {"%": text});
console.log('\nxml: \n' + xml);
``` 
Can you please have a look?

**Comment by tbouchnafa** [comment]
I get: 
```xml
<text><![CDATA[some thing here <document><property name="title"><![CDATA[Download]]]]><![CDATA[></property><property name="description"><![CDATA[Download]]></property></document> and some text here too]]></text>

```
but i expect: 
```xml
<text><![CDATA[some thing here <document><property name="title"><![CDATA[Download]]></property><property name="description"><![CDATA[Download]]></property></document> and some text here too]]></text>
```

Is this possible? 
Regards

**Comment by chilts** [comment]
Just pushed v1.2.4. Can you try that?

I didn't do a global replace ... oopse. :)

**Comment by tbouchnafa** [comment]
still get the same :| : 

```xml 
<text><![CDATA[some thing here <document><property name="title"><![CDATA[Download]]]]><![CDATA[></property><property name="description"><![CDATA[Download]]]]><![CDATA[></property></document> and some text here too]]></text>
```

**Comment by chilts** [comment]
That seems fine to me. xmlstarlet also says it's valid.

So I made it so that each `]]>` in the input CDATA is output as `]]]]><!CDATA[>`. 

This means that this:

{{{
<![CDATA[Download]]>
}}}

transforms into this:

{{{
<![CDATA[Download]]]]><![CDATA[>
}}}

There is no need to escape the `<![CDATA[` inside the CDATA since it will be ignored by any parser. The only thing that can't be in a CDATA is `]]>` which is why only that is escaped. Does that make sense?

**Comment by chilts** [comment]
Hi @tbouchnafa, can you confirm this is okay, or please re-post with what you get and what is expected.

**Comment by tbouchnafa** [comment]
Hi @chilts thanks for the fix, it fits now my needs
Thanks a lot!!
