### ISSUE TITLE
tape should not be a dependancy

### ISSUE THREAD

**Issue by ComLock** [chilts/data2xml#21]
I don't find any reference to tape here:
https://github.com/chilts/data2xml/blob/master/data2xml.js

It's listed twice in the package.json
https://github.com/chilts/data2xml/blob/master/package.json#L14-L15
https://github.com/chilts/data2xml/blob/master/package.json#L33-L34

It should probably only be a dev dependancy...

**Comment by chilts** [comment]
Thanks. I already had it as a devDependency, but I must have screwed it up when upgrading tape a month or so back. :) Released as v1.2.5.
