### ISSUE TITLE
Ordered Elements [Enhancement]

### ISSUE THREAD

**Issue by Eric24** [chilts/data2xml#24]
Great project--very useful! I had an idea that might be an easy enhancement for ordered elements (without relying on "de facto" JavaScript behavior), as well as adding support for multiple elements with the same name (as I've encountered on various APIs): If the second argument passed to data2xml is an array instead of an object, expect each array item to be an object that contains only one "top" property, then build the resulting XML by iterating the array "outside" of the existing object for..in.

**Comment by chilts** [comment]
Thanks for your kind comments.

I think I know what you mean, but would you be able to provide an example data structure and resulting XML so I know exactly what you're talking about. Perhaps two examples of a (1) this is how we do it now, and (2) this is how we **could** do it.

Many thanks.

**Comment by chilts** [comment]
Currently (for example) you can do this (taken from the ReadMe):

--

If you want an array, just put one in there:

```js
convert('TopLevelElement', {
    MyArray : [
        'Simple Value',
        {
            _attr : { type : 'colour' },
            _value : 'White',
        }
    ],
});
```

Will produce:

```xml
<TopLevelLement xmlns="http://chilts.org/xml/namespace">
    <MyArray>Simple Value</MyArray>
    <MyArray type="color">White</MyArray>
</TopLevelLement>
```

**Comment by chilts** [comment]
Ahah, I think you're talking about the top level element? If so, then yeah, that might work out quite well. :) If you can confirm and perhaps still give me an example, that'll be awesome.

**Comment by Eric24** [comment]
Thanks for the quick response. I'm tied up all day today, but I'll pull
together an example tomorrow so you can see exactly what I mean.
--Eric

**Comment by Eric24** [comment]
So here's an example of a simple (but currently impossible to do) XML
document:

<xml>
<speak>Hello</speak>
<play>https://xyz.xyz.com/audio.mp3</play>
<speak>Goodbye</speak>
</xml>

This is a fictitious document, based on a real example. Like many XML
documents, the order of the elements matters. Currently, JavaScript (at
least in node.js) does actually maintain object properties in the same
order they were added, so that's good but it's not guaranteed. But beyond
that, there is no way to have two properties with the same name if the
array approach won't work, like it doesn't here). My idea would be to allow
the document to be supplied to the XML generator as an array of separate
objects, where each object produces the next part of the XML), like this:

[
{'speak': 'Hello'},
{'play': 'https://xyz.xyz.com/audio.mp3'},
{'speak': 'Goodbye'},
]

Of course, each of the array item objects can support more complex
structures with attributes, etc., just like the current "one object per XML
document" syntax. In addition, a given object can contain just one XML
element or multiple elements, so that passing {...} is exactly the same as
passing [{...}].

My thoughts on this approach are:

   1. It's non-breaking (pass a single object or pass an array of objects)
   2. It's easy to implement (add an additional iterator at the array item
   level)
   3. It solves the element order problem without relying on anything that
   JavaScript does or doesn't do
   4. It removes the limitation of not being able to have multiple elements
   with the same name (in cases like this where an array won't work)
   5. It actually makes manipulation of the final XML document easier
   programmatically, using typical array building/management techniques

**Comment by bcomnes** [comment]
I would like to see this too.  

@Eric24's sugestion

```
[
{'speak': 'Hello'},
{'play': 'https://xyz.xyz.com/audio.mp3'},
{'speak': 'Goodbye'},
]
```

seem's like a good approach and is conceptually consistent with the rest of the API, although it seems like it might be incompatible with the existing API.  I do like it.  I'll think about it some more.

Another approach would be to something like this:

```js
convert('TopLevelElement', {
 MyArray : [
        'Simple Value',
        {
            _attr : { type : 'colour' },
            _value : 'Blue',
            _name: 'OverrideName'
        },
        {
            _attr : { type : 'colour' },
            _value : 'White',
        }
    ]
})
```
resulting in

```xml
<TopLevelLement xmlns="http://chilts.org/xml/namespace">
    <MyArray>Simple Value</MyArray>
    <OverrideName type="color">Blue</OverrideName>
    <MyArray type="color">White</MyArray>
</TopLevelLement>
```

The value of adding in something like `_name` to the complex value notation is that it looks like it would be really easy to implement, and not break 

I need this functionality for my use case, and would be willing to PR this feature once we settle on an approach.

**Comment by bcomnes** [comment]
Actually, please ignore me!  I got confused with the API and it does exactly what I want.

**Comment by chilts** [comment]
Migrated to https://gitlab.com/chilts/data2xml/issues/24
