### ISSUE TITLE
Need ability to control entitify() function.

### ISSUE THREAD

**Issue by skuznetsov** [chilts/data2xml#25]
First of all I love your project!
It small, simple, has no dependencies, so there is no dependency hell which is important to keep production environment sane.
The only feature I would love to request is ability to control the content of **entitify()**.
My use case is that sometimes I am receiving XML content that I am adding as a value to my JSON object but I want to keep them as a subsequent XML elements in final result.
I can do it by getting original **export.entitify()** function reference in parent code and wrapping it in my external **entitify()** function that will control if original **entitify()** should be called or it should return value as is and assign this function back to **exports.entitify** (which will be **data2xml.entitify = function(value){}** in my parent code).
It also can be done via callback as well but it will be extra code on your side.
My proposal is to add **export.** to **entitify()** in lines **157** and **176** (I don't see benefits of exposing it in line **75** though)

What do you think about it? Any cons?

All the Best!
Sergey.

**Comment by mikemcguire** [comment]
Especially for things like URLs

**Comment by chilts** [comment]
Sounds plausible. I think I know why the original poster wanted to just return the XML. @mikemcguire can you show me an example of what you want to do with URLs? Once I see examples I'll probably understand more. Thanks.

**Comment by chilts** [comment]
Migrated to https://gitlab.com/chilts/data2xml/issues/25
