### ISSUE TITLE
Problem with duplicate elements

### ISSUE THREAD

**Issue by jbull** [chilts/data2xml#26]
Thanks for the great work on this.  It's very useful.  I ran into an issue today in which I have to declare more then one element with the same name at the same level and when I do, only the first element gets generated into xml and the rest of them do not. In my example below the second invoice element doesn't get generated. Can you help?

Example: This is the intended output

		<Invoice>
			<CustomerRef>
				<FullName>Customer 123</FullName>
			</CustomerRef>
			<TxnDate>2017-01-05</TxnDate>
			<RefNumber>TEST-01</RefNumber>
			<BillAddress>
				<Addr1>1234 My Street</Addr1>
				<City>Somewhere</City>
				<State>CA</State>
				<PostalCode>11233</PostalCode>
				<Country>United States</Country>
			</BillAddress>
			<InvoiceLine>
				<ItemRef>
					<FullName>Product</FullName>
				</ItemRef>
				<Desc>Test Invoice line 1</Desc>
				<Quantity>40</Quantity>
				<Rate>75</Rate>
			</InvoiceLine>
			<InvoiceLine>
				<ItemRef>
					<FullName>Labor</FullName>
				</ItemRef>
				<Desc>Test Invoice line 2</Desc>
				<Quantity>32</Quantity>
				<Rate>55</Rate>
			</InvoiceLine>
		</Invoice>

		Heres my code:
		    var xml = convert(
        'MYXML',
        {
			Invoice: {
				CustomerRef: {
					FullName: 'Customer 123'
				},
				TxnDate: '2017-01-05',
				RefNumber:'TEST-01',
				BillAddress: {
					Addr1: '1234 My Street',
					City:'Somewhere',
					State:'CA',
					PostalCode:'11233',
					Country:'United States'
				},
				TermsRef:{
					FullName:'NET 30'
				},
				InvoiceLine: {
					ItemRef: {
						FullName: 'Product'
					},
					Desc:'Test Invoice line 1',
					Quantity:322,
					Rate:.02,
				},
				InvoiceLine: {
					ItemRef: {
						FullName: 'Labor'
					},
					Desc:'Test Invoice line 2',
					Quantity:32,
					Rate:55.00
				},
			},
        }
    );

**Comment by jbull** [comment]
Ha! I solved my issue. I reread the docs for the tenth time and realized that I needed to create an array for the invoice lines.  If it helps someone else here is an example:

InvoiceLine: [
	{
		ItemRef: {
			FullName: 'Product'
		},
		Desc:'Test Invoice line 1',
		Quantity:322,
		Rate:.02
	},
	{
		ItemRef: {
			FullName: 'Labor'
		},
		Desc:'Test Invoice line 2',
		Quantity:32,
		Rate:55.00
	}

**Comment by chilts** [comment]
Yeah, there is an example in the ReadMe. I don't think it needs anything extra. Feel free to PR something better if you think the docs need improving. :)
